"""
ask_z/api/schemas.py
─────────────────────
Pydantic v2 request / response models for the Ask-Z query API.
"""

from __future__ import annotations

from typing import Any
from pydantic import BaseModel, Field, field_validator


# ── Request ────────────────────────────────────────────────────────────────────


class QueryRequest(BaseModel):
    """Body for POST /api/v1/query"""

    query: str = Field(
        ...,
        min_length=3,
        max_length=2048,
        description="Natural-language question about IBM Z / Spyre.",
        examples=["How does the Spyre attention operator handle TTFT?"],
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of context chunks to return after reranking.",
    )
    # Optional: caller can override the rerank threshold per request.
    rerank_threshold: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description=(
            "Minimum cross-encoder score to include a chunk. "
            "Set to 0.0 to return top_k regardless of absolute score."
        ),
    )

    @field_validator("query")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        return v.strip()


# ── Per-chunk context block ────────────────────────────────────────────────────


class ContextChunk(BaseModel):
    """A single retrieved and reranked knowledge chunk."""

    text: str = Field(..., description="Raw chunk text passed to the LLM.")
    score: float = Field(..., description="Cross-encoder reranking score.")
    rrf_score: float = Field(
        ..., description="Reciprocal Rank Fusion score before reranking."
    )
    rank: int = Field(..., description="1-based position after reranking.")

    # Metadata mirroring the Elasticsearch document schema.
    file_path: str
    source_url: str
    doc_type: str  # code | doc | ADR | test
    component_tag: str
    last_updated: str
    git_blame_author: str
    version: str
    chunk_index: int
    content_hash: str
    staleness_ttl_flag: bool


# ── Pipeline diagnostics (returned in response for transparency) ───────────────


class PipelineDiagnostics(BaseModel):
    """Timing and count diagnostics for the full retrieval pipeline."""

    hyde_ms: float = Field(..., description="HyDE generation + embedding time (ms).")
    bm25_hits: int = Field(
        ..., description="BM25 candidates returned by Elasticsearch."
    )
    knn_hits: int = Field(..., description="KNN candidates returned by Elasticsearch.")
    rrf_candidates: int = Field(..., description="Unique candidates after RRF fusion.")
    reranked_count: int = Field(..., description="Candidates scored by cross-encoder.")
    dropped_below_threshold: int = Field(
        ..., description="Candidates dropped by score filter."
    )
    total_ms: float = Field(..., description="Total end-to-end pipeline latency (ms).")


# ── Response ───────────────────────────────────────────────────────────────────


class QueryResponse(BaseModel):
    """Response body for POST /api/v1/query"""

    query: str = Field(..., description="The original user query.")
    hyde_hypothesis: str = Field(
        ..., description="The synthetic answer generated by HyDE."
    )
    answer: str = Field(
        ...,
        description=(
            "Grounded answer generated by Granite with inline [Source: ...] citations."
        ),
    )
    chunks: list[ContextChunk] = Field(
        ...,
        description="Top-k reranked context chunks, ordered by cross-encoder score descending.",
    )
    diagnostics: PipelineDiagnostics


# ── Error response ─────────────────────────────────────────────────────────────


class ErrorDetail(BaseModel):
    code: str
    message: str
    detail: Any = None


class ErrorResponse(BaseModel):
    error: ErrorDetail
